version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push Docker image
          command: |
            set +e

            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo "Building Edge for master"
              docker tag app kanopi/ci:edge
              docker push kanopi/ci:edge
            elif [[ -n "${CIRCLE_BRANCH}" ]]; then
              echo "Building Edge for ${CIRCLE_BRANCH}"
              BRANCH=$(echo $CIRCLE_BRANCH | sed -e 's/[^A-Za-z0-9]/-/g' | awk '{print tolower($0)}')
              docker tag app kanopi/ci:edge-${BRANCH}
              docker push kanopi/ci:edge-${BRANCH}
            fi

            if [[ -n "${CIRCLE_TAG}" ]]; then
              echo "Building Version"

              docker tag app kanopi/ci:${CIRCLE_TAG}
              docker push kanopi/ci:${CIRCLE_TAG}

              echo "Building Latest"
              docker tag app kanopi/ci:latest
              docker push kanopi/ci:latest
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build