version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish_branch:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - publish_tag:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
        environment:
          DOCKER_IMAGE_NAME: kanopi/ci
          CONTAINER_USER: circleci
          CONTAINER_NAME: app
          DOCKER_CACHED: /tmp/workspace/app.tar

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: docker-{{ .Branch }}
          paths:
            - /tmp/workspace/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ${DOCKER_CACHED} | true
      - run:
          name: Build application Docker image
          command: docker build -t ${DOCKER_IMAGE_NAME}:latest .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /tmp/workspace
            docker save -o ${DOCKER_CACHED} ${DOCKER_IMAGE_NAME}
      - save_cache:
          key: docker-{{ .Branch }}
          paths:
            - /tmp/workspace/app.tar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ./app.tar

  test:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i ${DOCKER_CACHED}
      - run:
          name: Install BATS-CORE
          command: |
            set -e
            git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
            cd /tmp/bats-core
            sudo /tmp/bats-core/install.sh /usr/local
      - checkout
      - run:
          name: Create Docker Volume
          command: docker run -d -v /var/www --name project-root circleci/buildpack-deps:stretch /bin/true
      - run:
          name: Download Drupal Project
          command: |
            git clone --depth=1 https://git.drupalcode.org/project/drupal.git project
            docker cp project project-root:/var/www
      - run:
          name: Run Tests
          command: |
            set -e
            bats -r tests

  publish_branch:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i ${DOCKER_CACHED}
      - deploy:
          name: Push Docker image
          command: |
            set -e
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag ${DOCKER_IMAGE_NAME}:latest ${DOCKER_IMAGE_NAME}:edge-${CIRCLE_BRANCH}
            docker push ${DOCKER_IMAGE_NAME}:edge-${CIRCLE_BRANCH}
            docker tag ${DOCKER_IMAGE_NAME}:latest ${DOCKER_IMAGE_NAME}:edge-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
            docker push ${DOCKER_IMAGE_NAME}:edge-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}

  publish_tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i ${DOCKER_CACHED}
      - deploy:
          name: Push Docker image
          command: |
            set -e
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag ${DOCKER_IMAGE_NAME}:latest ${DOCKER_IMAGE_NAME}:${CIRCLE_TAG}
            docker push ${DOCKER_IMAGE_NAME}:${CIRCLE_TAG}
            docker push ${DOCKER_IMAGE_NAME}:latest
